# Generated by Django 4.2.30 on 2026-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GreatMenProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("spots", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gmm/programs/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Great Men Program",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ImpactGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text='Display value e.g. "500+" or "12"', max_length=20
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0-100 percentage"
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Impact Goal",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("profession", models.CharField(blank=True, max_length=200)),
                ("motivation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Volunteer Application",
                "ordering": ["-created_at"],
            },
        ),
    ]
