# Generated by Django 4.2.30 on 2026-05-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogarticle",
            name="featured_image",
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="author_bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("fr", "French"),
                    ("pt", "Portuguese"),
                    ("ar", "Arabic"),
                    ("zh", "Chinese"),
                ],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text='["tag1", "tag2"]'
            ),
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="thumbnail_alt",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="color",
            field=models.CharField(blank=True, default="#d4a574", max_length=20),
        ),
        migrations.AlterField(
            model_name="blogarticle",
            name="content",
            field=models.TextField(help_text="Supports Markdown"),
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                ("author_email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogarticle",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.blogcomment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogShareCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter / X"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("copy_link", "Copy Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_counts",
                        to="blog.blogarticle",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "platform")},
            },
        ),
        migrations.CreateModel(
            name="BlogReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("love", "❤️ Love"),
                            ("fire", "🔥 Fire"),
                            ("clap", "👏 Clap"),
                            ("mind_blown", "🤯 Mind Blown"),
                            ("insightful", "💡 Insightful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="blog.blogarticle",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="BlogLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="blog.blogarticle",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "fingerprint")},
            },
        ),
    ]
