# Generated by Django 4.2.30 on 2026-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_add_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="blogarticle",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
