# Generated by Django 4.2.30 on 2026-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_add_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
