# Generated by Django 4.2.30 on 2026-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment_default_not_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="content",
            field=models.TextField(
                help_text="Supports Markdown. To place an uploaded image at an exact point in the article (instead of it only appearing in the gallery), scroll to the Images section below, save once so the snippet fields populate, then copy the snippet for the placement you want (full width / float left / float right / centred) and paste it into the content at that point."
            ),
        ),
    ]
