# Generated by Django 4.2.30 on 2026-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_add_subject_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
