# Generated by Django 4.2.30 on 2026-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_add_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("collaboration", "Collaboration"),
                    ("project", "Project Inquiry"),
                    ("speaking", "Speaking Engagement"),
                    ("donation", "Donation / Sponsorship"),
                    ("mentorship", "Mentorship — Great Men Moves"),
                    ("music", "Gospel Music"),
                    ("book", "Book — The Jar You Left Behind"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
