# Generated by Django 4.2.30 on 2026-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("meteorology", "Meteorology"),
                    ("software", "Software Development"),
                    ("data_science", "Data Science"),
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("devops", "DevOps"),
                    ("design", "Design"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
