# Generated by Django 4.2.30 on 2026-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_skill_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text='e.g. "2024 – Present" or "2019 – 2023"',
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower = appears first"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-is_current"],
            },
        ),
    ]
