# Generated by Django 4.2.30 on 2026-06-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_career_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
