# Generated by Django 4.2.30 on 2026-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="music/"),
                ),
                ("youtube_url", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                ("apple_music_url", models.URLField(blank=True)),
                ("soundcloud_url", models.URLField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(blank=True, help_text="e.g. 3:45", max_length=10),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-is_featured", "order", "-release_date"],
            },
        ),
    ]
