# Generated by Django 4.2.30 on 2026-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
