# Generated by Django 4.2.30 on 2026-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_add_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
