# Generated by Django 4.2.30 on 2026-05-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
                ("author", models.CharField(default="Msizi", max_length=200)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("amazon_url", models.URLField(blank=True)),
                (
                    "preview_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="books/previews/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-release_date"],
            },
        ),
        migrations.CreateModel(
            name="BookTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=200)),
                ("author_title", models.CharField(blank=True, max_length=200)),
                (
                    "author_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="books/testimonials/"
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
