# Generated by Django 4.2.30 on 2026-05-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors_note",
            field=models.TextField(
                blank=True, help_text="Author's personal note shown on the book page"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="price_kes",
            field=models.PositiveIntegerField(
                default=1500, help_text="Pre-order price in KES"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="price_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=9.99,
                help_text="Pre-order price in USD",
                max_digits=6,
            ),
        ),
        migrations.CreateModel(
            name="BookChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle / theme of the chapter",
                        max_length=200,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Short preview shown on the book page"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "number"],
            },
        ),
    ]
