# Generated by Django 4.2.30 on 2026-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_add_chapter_and_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktestimonial",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Not shown publicly — for following up with the reader",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="booktestimonial",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
