# Generated by Django 4.2.30 on 2026-05-27 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="E.164 format: 254XXXXXXXXX",
                        max_length=20,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        default="Broken Souls — Pre-Order", max_length=300
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("mpesa", "M-Pesa"), ("card", "Card (Stripe)")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "mpesa_checkout_request_id",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "mpesa_merchant_request_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("stripe_client_secret", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
