# Generated by Django 4.2.30 on 2026-07-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preorder",
            name="product_name",
            field=models.CharField(default="The Jar You Left Behind — Pre-Order", max_length=300),
        ),
    ]
